Repository Laravel-Backpack/theme-coreuiv4, pull requests merged in 2023-06, with the labels that each got.

#11 move most widgets to CRUD
  resources/views/widgets/alert.blade.php
  resources/views/widgets/card.blade.php
  resources/views/widgets/div.blade.php
  resources/views/widgets/inc/wrapper_end.blade.php
  resources/views/widgets/inc/wrapper_start.blade.php
  resources/views/widgets/jumbotron.blade.php
  resources/views/widgets/script.blade.php
  resources/views/widgets/style.blade.php
  resources/views/widgets/view.blade.php
  src/AddonServiceProvider.php
  src/AutomaticServiceProvider.php
Labels: Priority: MUST

#18 remove prism css
  resources/views/inc/theme_styles.blade.php
Labels: Priority: MUST

#21 style-page-heading-section
  resources/assets/css/coreui4.css
Labels: Priority: MUST, Size: XS

#16 add view components for menus
  resources/views/components/menu-dropdown-item.blade.php
  resources/views/components/menu-dropdown.blade.php
  resources/views/components/menu-item.blade.php
  resources/views/components/menu-separator.blade.php
Labels: Priority: MUST

#25 Use theme service provider
  resources/assets/css/coreui4.css
  resources/views/auth/login.blade.php
  resources/views/inc/main_header.blade.php
  resources/views/inc/theme_styles.blade.php
  src/AddonServiceProvider.php
  src/AutomaticServiceProvider.php
Labels: Priority: MUST, Priority: SHOULD, Size: XS

#29 Fix User Dropdown UI
  resources/views/inc/menu_user_dropdown.blade.php
Labels: Priority: MUST, bug

#30 add dropdown menu header component
  resources/views/components/menu-dropdown-header.blade.php
Labels: Priority: MUST, Priority: SHOULD
